// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Partner struct {
	ID       int32          `json:"id"`
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Balance  float64        `json:"balance"`
	Active   bool           `json:"active"`
	StripeID sql.NullString `json:"stripe_id"`
	WiseID   sql.NullString `json:"wise_id"`
	Reason   sql.NullString `json:"reason"`
}
