// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	ActivatePartner(ctx context.Context, id int32) error
	ChangePassword(ctx context.Context, arg *ChangePasswordParams) error
	CheckUserEmail(ctx context.Context, email string) (bool, error)
	GetPartnerStripeCustumerID(ctx context.Context, id int32) (sql.NullString, error)
	SetNewStripeAccount(ctx context.Context, arg *SetNewStripeAccountParams) error
}

var _ Querier = (*Queries)(nil)
